name: Obliga origen de PR a 'development' si el destino es 'main'

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  enforce-source-branch:
    # Solo correr cuando el PR tenga como base main
    if: ${{ github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check PR head branch
        run: |
          echo "Target (base) branch: ${{ github.base_ref }}"
          echo "Source (head) branch: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "development" ]; then
            echo "::error ::Pull requests a main deben provenir de la rama 'development'."
            echo "::error ::Abre un PR que fusione 'development' en 'main' (o fusiona tu branch en 'development' primero)."
            exit 1
          fi
